spring.application.name=sping-batch-application

server.port = 2025
#spring.batch.jdbc.initialize-schema=always
#spring.sql.init.mode=always

#spring.batch.job.enabled=false
spring.batch.job.name=migrationJob

spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/spring-batch?allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=son
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.unversitydatasource.jdbc-url=jdbc:mysql://localhost:3306/university?allowPublicKeyRetrieval=true
spring.unversitydatasource.username=root
spring.unversitydatasource.password=son
spring.unversitydatasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.postgresdatasource.jdbc-url=jdbc:postgresql://localhost:5432/university
spring.postgresdatasource.username=postgres
spring.postgresdatasource.password=123
spring.postgresdatasource.driver-class-name=org.postgresql.Driver

#logging.level.org.springframework.batch=debug
#logging.level.org.springframework.jdbc=debug
#logging.level.org.zaxxer.hikari=debug
#logging.level.org.hibernate=debug
