spring.application.name=sping-batch-application

server.port = 2025
#spring.batch.jdbc.initialize-schema=always
#spring.sql.init.mode=always

#spring.batch.job.enabled=false
spring.batch.job.name=restChunkJob

spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/spring-batch?allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=son
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#logging.level.org.springframework.batch=debug
#logging.level.org.springframework.jdbc=debug
#logging.level.org.zaxxer.hikari=debug
#logging.level.org.hibernate=debug
